name=CYD_Panel
version=0.0.0
author=Jaap Danielse <j.danielse@gmail.com>
maintainer=Jaap Danielse 
sentence=Cheap Yellow Display Arduino Experiment Control Library
paragraph=Control and display functions on the Cheap Yellow Display
category=Other
url=https://github.com/JaapDanielse/CYD_Panel/
architectures=esp32
depends=TFT_eSPI, XPT2046_Touchscreen